<a href="https://colab.research.google.com/github/meenalsingh5925-creator/Getting-started-with-hugging-face/blob/main/Gettingstartedwithhuggingface(part1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [85]:
# @title
feedback_data = {
    "feedback": [
        "The course content was very well sturctured.",
        "The lectures were easy to understand.",
        "I really enjoyed the practical sessions and assignments.",
        "The instructor explained concepts clearly.",
        "The workload was heavy and deadlines were stressful.",
        "The examples used in class made learning easy.",
        "I felt the course could have been more interactive."
    ]
}

In [86]:
# transformers
# datasets
# evaluate
# accelerate

In [87]:
!pip install -q "transformers<5.0.0" datasets accelerate evaluate

In [88]:
import transformers, accelerate, datasets, evaluate
print(transformers.__version__)

4.57.6

In [90]:
print(accelerate.__version__)
print(datasets.__version__)
print(evaluate.__version__)

1.14.0
4.8.5
0.4.6

In [89]:
from transformers import pipeline

classifier = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cuda:0

In [58]:
classifier("The movie was not bad")

[{'label': 'POSITIVE', 'score': 0.9987165927886963}]

In [59]:
classifier(["The movie was not bad", "I hate this so much"])

[{'label': 'POSITIVE', 'score': 0.9987165927886963},
 {'label': 'NEGATIVE', 'score': 0.9995144605636597}]

In [60]:
generator = pipeline("text-generation")
g = generator("In this course, we will teach you to")
print(g[0]['generated_text'])

No model was supplied, defaulted to openai-community/gpt2 and revision 607a30d (https://huggingface.co/openai-community/gpt2).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cuda:0
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

In this course, we will teach you to analyze and take advantage of the most common problems in Java programming, including problems with the syntax, behavior, and behavior of Java objects. You will learn how to define a Java object and how to use it to handle many commonly encountered problems.

This course is designed to give you an understanding of the Java programming language and its properties. To help you develop your own Java object, you will use a Java object management system.

The course is designed to be a hands-on introduction to Java programming knowledge, and at the same time to help you develop your own Java object management system.

In this course, we will talk about defining a Java object and how to use it to handle many common problems in Java.

We will explore the many different ways in which Java properties are used in the Java programming language, particularly by Java developers who need to maintain a consistent database of Java objects.

We will discuss the differences between Java objects and Java objects in Java, and we will also cover the differences between Java properties and properties of Java object types.

Course Description

This course is designed to be a hands-on introduction to Java programming knowledge, and at the same time to help you develop your own Java object management system.

In [61]:
generator = pipeline("text-generation", model = "HuggingFaceTB/SmolLM2-360M")
g = generator("In this course, we will teach you to", max_new_tokens = 30)
print(g[0]['generated_text'])

Device set to use cuda:0
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

In this course, we will teach you to use these ideas to solve complex engineering problems.

## Chapter 1: The Nature of Science

What is science? What is the scientific

In [62]:
generator.model.name_or_path

'HuggingFaceTB/SmolLM2-360M'

In [91]:
import pandas as pd

feedback_data = {
    "feedback": [
        "The course content was very well structured.",
        "The lectures were easy to understand.",
        "I really enjoyed the practical sessions and assignments.",
        "The instructor explained concepts clearly.",
        "The workload was heavy and deadlines were stressful.",
        "The examples used in class made learning easy.",
        "I felt the course could have been more interactive."
    ]
}

In [64]:
df = pd.DataFrame(feedback_data)
df

                                            feedback
0       The course content was very well structured.
1              The lectures were easy to understand.
2  I really enjoyed the practical sessions and as...
3         The instructor explained concepts clearly.
4  The workload was heavy and deadlines were stre...
5     The examples used in class made learning easy.
6  I felt the course could have been more interac...

In [92]:
senti_p = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cuda:0

In [66]:
summ_p = pipeline("summarization")

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cuda:0

In [93]:
all_feedbacks = df["feedback"].tolist()
all_feedbacks

['The course content was very well structured.',
 'The lectures were easy to understand.',
 'I really enjoyed the practical sessions and assignments.',
 'The instructor explained concepts clearly.',
 'The workload was heavy and deadlines were stressful.',
 'The examples used in class made learning easy.',
 'I felt the course could have been more interactive.']

In [94]:
sentiments = senti_p(all_feedbacks)
sentiments

[{'label': 'POSITIVE', 'score': 0.9998527765274048},
 {'label': 'POSITIVE', 'score': 0.9949953556060791},
 {'label': 'POSITIVE', 'score': 0.9998310804367065},
 {'label': 'POSITIVE', 'score': 0.9992693066596985},
 {'label': 'NEGATIVE', 'score': 0.9877687096595764},
 {'label': 'POSITIVE', 'score': 0.9967496395111084},
 {'label': 'NEGATIVE', 'score': 0.9993316531181335}]

In [69]:
all_labels = [s['label'] for s in sentiments]
all_labels

['POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'NEGATIVE',
 'POSITIVE',
 'NEGATIVE']

In [70]:
all_scores = [s['score'] for s in sentiments]
all_scores

[0.9998527765274048,
 0.9949953556060791,
 0.9998310804367065,
 0.9992693066596985,
 0.9877687096595764,
 0.9967496395111084,
 0.9993316531181335]

In [95]:
df['Sentiment'] = all_labels
df['Score'] = all_scores

df

                                            feedback Sentiment     Score
0       The course content was very well structured.  POSITIVE  0.999853
1              The lectures were easy to understand.  POSITIVE  0.994995
2  I really enjoyed the practical sessions and as...  POSITIVE  0.999831
3         The instructor explained concepts clearly.  POSITIVE  0.999269
4  The workload was heavy and deadlines were stre...  NEGATIVE  0.987769
5     The examples used in class made learning easy.  POSITIVE  0.996750
6  I felt the course could have been more interac...  NEGATIVE  0.999332

In [72]:
combined_feedback = " ".join(df["feedback"].tolist())
combined_feedback

'The course content was very well structured. The lectures were easy to understand. I really enjoyed the practical sessions and assignments. The instructor explained concepts clearly. The workload was heavy and deadlines were stressful. The examples used in class made learning easy. I felt the course could have been more interactive.'

In [73]:
summ_p(combined_feedback, max_length = 38, min_length = 30)

[{'summary_text': ' The workload was heavy and deadlines were stressful . The examples used in class made learning easy . I felt the course could have been more interactive .'}]

# Tokenizer

In [74]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

In [75]:
encoding = tokenizer("Huggingface is amazing!")
encoding

{'input_ids': [101, 17662, 12172, 2003, 6429, 999, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1]}

In [76]:
tokenizer.convert_ids_to_tokens(encoding['input_ids'])

['[CLS]', 'hugging', '##face', 'is', 'amazing', '!', '[SEP]']

In [77]:
encoding = tokenizer("Huggingface is amazing!", "I am enjoying all this")
encoding

{'input_ids': [101, 17662, 12172, 2003, 6429, 999, 102, 1045, 2572, 9107, 2035, 2023, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [78]:
tokenizer(["Huggingface is amazing!", "I am enjoying all this", "Hi"], padding = "max_length",
          max_length = 6, truncation = True)

{'input_ids': [[101, 17662, 12172, 2003, 6429, 102], [101, 1045, 2572, 9107, 2035, 102], [101, 7632, 102, 0, 0, 0]], 'token_type_ids': [[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 0, 0, 0]]}

In [79]:
tokenizer(["Huggingface is amazing!", "I am enjoying all this", "Hi"], padding = "max_length",
          max_length = 6, truncation = True, return_tensors = "pt")

{'input_ids': tensor([[  101, 17662, 12172,  2003,  6429,   102],
        [  101,  1045,  2572,  9107,  2035,   102],
        [  101,  7632,   102,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 0, 0, 0]])}

In [80]:
tokenizer(["Huggingface is amazing!", "I am enjoying all this", "Hi"], padding = "max_length",
          max_length = 6, truncation = True, return_tensors = "np")

{'input_ids': array([[  101, 17662, 12172,  2003,  6429,   102],
       [  101,  1045,  2572,  9107,  2035,   102],
       [  101,  7632,   102,     0,     0,     0]]), 'token_type_ids': array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]]), 'attention_mask': array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0]])}

# Models

In [81]:
from transformers import AutoModel

In [82]:
model = AutoModel.from_pretrained("bert-base-uncased")
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
          (intermediate_act_fn): GELUActivation()
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
  (pooler): BertPooler(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (activation): Tanh()
  )
)

In [83]:
dir(model)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_adjust_missing_and_unexpected_keys',
 '_apply',
 '_auto_class',
 '_backward_compatibility_gradient_checkpointing',
 '_backward_hooks',
 '_backward_pre_hooks',
 '_buffers',
 '_call_impl',
 '_can_compile_fullgraph',
 '_can_record_outputs',
 '_can_set_attn_implementation',
 '_check_and_adjust_attn_implementation',
 '_checkpoint_conversion_mapping',
 '_compiled_call_impl',
 '_convert_head_mask_to_5d',
 '_copy_lm_head_original_to_resized',
 '_create_repo',
 '_dispatch_accelerate_model',
 '_ep_plan',
 '_fix_state_dict_key_on_load',
 '_fix_state_dict_key_on_save',
 '_fix_state_dict_keys_on_save',
 '_flash_attn_2_can_dispatch',
 '_flash_attn_3_can_dispatch',
 '_flex_attn_can_dispatch',
 '_forward_hooks',
 '_forward_hooks_always_called',
 '_forward_hooks_with_kwargs',
 '_forward_pre_hooks',
 '_forward_pre_hooks_with_kwargs',
 '_from_config',
 '_get_backward_hooks',
 '_get_backward_pre_hooks',
 '_get_files_timestamps',
 '_get_key_renaming_mapping',
 '_get_name',
 '_get_no_split_modules',
 '_get_resized_embeddings',
 '_get_resized_lm_head',
 '_hf_peft_config_loaded',
 '_hook_rss_memory_post_forward',
 '_hook_rss_memory_pre_forward',
 '_init_added_embeddings_weights_with_mean',
 '_init_added_lm_head_bias_with_mean',
 '_init_added_lm_head_weights_with_mean',
 '_init_weights',
 '_initialize_missing_keys',
 '_initialize_weights',
 '_input_embed_layer',
 '_is_full_backward_hook',
 '_is_hf_initialized',
 '_is_stateful',
 '_keep_in_fp32_modules',
 '_keep_in_fp32_modules',
 '_keep_in_fp32_modules_strict',
 '_keep_in_fp32_modules_strict',
 '_keys_to_ignore_on_load_missing',
 '_keys_to_ignore_on_load_unexpected',
 '_keys_to_ignore_on_save',
 '_load_from_flax',
 '_load_from_state_dict',
 '_load_from_tf',
 '_load_pretrained_model',
 '_load_state_dict_post_hooks',
 '_load_state_dict_pre_hooks',
 '_maybe_warn_non_full_backward_hook',
 '_modules',
 '_move_missing_keys_from_meta_to_cpu',
 '_named_members',
 '_no_split_modules',
 '_no_split_modules',
 '_non_persistent_buffers_set',
 '_parameters',
 '_pp_plan',
 '_pp_plan',
 '_prune_heads',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_replicate_for_data_parallel',
 '_resize_token_embeddings',
 '_save_to_state_dict',
 '_sdpa_can_dispatch',
 '_set_default_dtype',
 '_set_gradient_checkpointing',
 '_skip_keys_device_placement',
 '_slow_forward',
 '_state_dict_hooks',
 '_state_dict_pre_hooks',
 '_supports_attention_backend',
 '_supports_flash_attn',
 '_supports_flex_attn',
 '_supports_sdpa',
 '_tie_encoder_decoder_weights',
 '_tie_or_clone_weights',
 '_tied_weights_keys',
 '_tp_plan',
 '_tp_plan',
 '_tp_size',
 '_upload_modified_files',
 '_version',
 '_wrapped_call_impl',
 'active_adapters',
 'add_adapter',
 'add_memory_hooks',
 'add_model_tags',
 'add_module',
 'apply',
 'attn_implementation',
 'base_model',
 'base_model_prefix',
 'bfloat16',
 'buffers',
 'call_super_init',
 'can_generate',
 'can_record_outputs',
 'children',
 'compile',
 'config',
 'config_class',
 'cpu',
 'create_extended_attention_mask_for_decoder',
 'cuda',
 'delete_adapter',
 'dequantize',
 'device',
 'disable_adapters',
 'disable_input_require_grads',
 'double',
 'dtype',
 'dummy_inputs',
 'dump_patches',
 'embeddings',
 'enable_adapters',
 'enable_input_require_grads',
 'encoder',
 'estimate_tokens',
 'eval',
 'extra_repr',
 'float',
 'floating_point_ops',
 'forward',
 'framework',
 'from_pretrained',
 'generation_config',
 'get_adapter_state_dict',
 'get_buffer',
 'get_compiled_call',
 'get_correct_attn_implementation',
 'get_decoder',
 'get_extended_attention_mask',
 'get_extra_state',
 'get_head_mask',
 'get_init_context',
 'get_input_embeddings',
 'get_memory_footprint',
 'get_output_embeddings',
 'get_parameter',
 'get_parameter_or_buffer',
 'get_position_embeddings',
 'get_submodule',
 'gradient_checkpointing_disable',
 'gradient_checkpointing_enable',
 'half',
 'init_weights',
 'initialize_weights',
 'invert_attention_mask',
 'ipu',
 'is_backend_compatible',
 'is_gradient_checkpointing',
 'is_parallelizable',
 'kernelize',
 'load_adapter',
 'load_state_dict',
 'load_tf_weights',
 'loss_function',
 'loss_type',
 'main_input_name',
 'model_tags',
 'modules',
 'mtia',
 'name_or_path',
 'named_buffers',
 'named_children',
 'named_modules',
 'named_parameters',
 'num_parameters',
 'parameters',
 'pooler',
 'position_embedding_type',
 'post_init',
 'pp_plan',
 'prune_heads',
 'push_to_hub',
 'register_backward_hook',
 'register_buffer',
 'register_for_auto_class',
 'register_forward_hook',
 'register_forward_pre_hook',
 'register_full_backward_hook',
 'register_full_backward_pre_hook',
 'register_load_state_dict_post_hook',
 'register_load_state_dict_pre_hook',
 'register_module',
 'register_parameter',
 'register_state_dict_post_hook',
 'register_state_dict_pre_hook',
 'requires_grad_',
 'reset_memory_hooks_state',
 'resize_position_embeddings',
 'resize_token_embeddings',
 'retrieve_modules_from_names',
 'reverse_bettertransformer',
 'save_pretrained',
 'set_adapter',
 'set_attn_implementation',
 'set_decoder',
 'set_extra_state',
 'set_input_embeddings',
 'set_output_embeddings',
 'set_submodule',
 'share_memory',
 'smart_apply',
 'state_dict',
 'supports_gradient_checkpointing',
 'supports_pp_plan',
 'supports_tp_plan',
 'tie_embeddings_and_encoder_decoder',
 'tie_weights',
 'to',
 'to_bettertransformer',
 'to_empty',
 'tp_plan',
 'tp_size',
 'train',
 'training',
 'type',
 'use_kernels',
 'warn_if_padding_and_no_attention_mask',
 'warnings_issued',
 'xpu',
 'zero_grad']

In [84]:
model.name_or_path

'bert-base-uncased'